config/routes.rb
Tipp5::Application.routes.draw do
  
  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :cups do
    member do
      get 'automate'
    end
    resources :rounds do
    end
  end

  resources :games do
    collection do
      get :result_index
    end
    member do
      get :fix_result
      put :save_result
    end
  end
  
  resources :bets

  resources :posts do
    collection do
      get :new_userpost
    end
  end

  resources :teams

  resources :communities do
    collection do
      get :kick_out
      get :invite
    end
  end

  
  root :to => 'pages#home'

  match '/admin',     :to => 'pages#admin'
  match '/userpage',  :to => 'pages#userpage'
  match '/adminpage', :to => 'pages#adminpage'
  match '/about',     :to => 'pages#about'
  match '/rules',     :to => 'pages#rules'
  match '/impressum', :to => 'pages#impressum'
  
  match '/abgabe',    :to => 'bets#abgabe'
  match '/uebersicht', :to => 'bets#index'
  match '/ranking',   :to => 'bets#ranking'

  match '/news',      :to => 'posts#news'

  match '/join',      :to => 'communities#join'
  match '/leave',     :to => 'communities#leave'

end

app/views/pages/_community_news.html.erb
<div class="main_content">
	<h2>Community-Neuigkeiten von "<%= link_to @community.name, @community %>"</h2>
	<p></p>

	<%= will_paginate @posts %>

	<div class="user_post_button">
		<%= link_to "Beitrag schreiben", new_userpost_posts_path, :class => "btn" %>
	</div>

	<% @posts.each do |post| %>
		<div class="post_preview">
			
			<h4><%= post.headline %></h4>
			<%= post.created_at.strftime("%d.%m.%y %H:%M")%>
			<% unless post.user_id.nil? %>
				 | <%= link_to User.find(post.user_id).username, user_path(User.find(post.user_id)) %>
			<% end %>
			<p><%= simple_format(truncate(post.content, :length => 500, :separator => ' ')) %>
			<% if post.content.length > 500 %>
				<%= link_to "mehr", post %>
			<% end %></p>
			<% if post.user_id === current_user.id %>
				<%= link_to "Beitrag bearbeiten", edit_post_path(post) %>
			<% end %>
		</div>
	<% end %>

	<%= will_paginate @posts %>
</div>

app/views/pages/_feedback.html.erb
<div class="well">
	<h4>Meinungen? Vorschläge? Fehlermeldungen?</h4>
	<br>
	<p><a target="_blank" class="btn btn-success btn-large" href="http://blog.tipp2.net/?page_id=10">Feedback geben</a></p>
	<p>... im tipp2-Blog</p>
</div>

app/views/pages/_next_games.html.erb
	<div class="well">
		<h2>Nächste Spiele</h2>
		<table class="table table-striped table-condensed">
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<% if user_signed_in? %>
					<th>Tipp</th>
					<th>Anstoß</th>
				<% else %>
					<th></th>
					<th></th>
				<% end %>
			</tr>
			<% @games.each do |game| %>
				<tr>
					<% home_team = Team.find(game.home_team) %>
					<% away_team = Team.find(game.away_team) %>
					<td><%= truncate(home_team.acronym, :length => 10) %></td>
					<td> - </td>
					<td><%= truncate(away_team.acronym, :length => 10) %></td>
					<% if user_signed_in? %>
						<% user_bet = current_user.bets.where(:game_id => game.id).first %>
						<% if user_bet.nil? %>
							<td>- : -</td>
						<% else %>
							<td><%= user_bet.home_bet %> : <%= user_bet.away_bet %></td>
						<% end %>
					<% end %>
					<td><%= distance_of_time_in_words(Time.now, game.kickoff) %></td>
				</tr>	
			<% end %>
		</table>
	</div>

app/views/pages/_tipp2_news.html.erb
<div class="main_content">
	<h2>Neuigkeiten</h2>
	<p></p>
	<% @posts.each do |post| %>
		<%= post.created_at.strftime("%d.%m.%y %H:%M")%>
		<h4><%= post.headline %></h4>
		<p><%= truncate(simple_format(post.content), :length => 500, :separator => ' ') %>
		<% if post.content.length > 500 %>
			<%= link_to "mehr", post %>
		<% end %>
		</p>
	<% end %>
</div>

app/views/pages/_welcome.html.erb
<h1>Das Fußball-Tippspiel</h1>
<p>Melde Dich an, tippe auf Spiele, sammel Punkte und beeindrucke deine Freunde mit Fussball-Sachverstand :-)</p>

<p><%= link_to "Jetzt registrieren", new_user_registration_path, :class => "btn btn-success btn-large" %></p>
<%= link_to "Schon registriert? Log in!",  user_session_path, :class => "zusatzlink" %>

app/views/pages/about.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">

			<h2>Über das Projekt</h2>

			<p>tipp2 ist ein klassisches Fußball-Tippspiel. Melde Dich an, tippe auf Spiele, sammel Punkte und gewinne gegen andere Spieler.</p>

			<p>Diese Website ist ein privates Hobbyprojekt, welches ständig weiterentwickelt wird. Daher kann es immer wieder zu technischen Schwierigkeiten kommen, die ich schon jetzt entschuldige. Ich kann leider keine Verantwortung für Datenverlust oder nicht korrekt funktionierende Tippabrechnungen übernehmen. Falls etwas nicht funktioniert, nehmt bitte Kontakt mit mir auf.</p>

			<p>Alles weitere zum Entwicklungs-Status, zu geplanten Features, zum Drumherum findet ihr im <a target="_blank" href="http://blog.tipp2.net/">tipp2-Blog</a></p>


			<h4>Technisches</h4>

			<p>tipp2 ist eine Applikation basierend auf dem Web-Framework '<a href="http://rubyonrails.org/">Ruby on Rails</a>'. Als Basis für das Layout wurde <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap 2.0</a> verwendet.</p>

			<h4>Feedback</h4>

			<p>Ich freue mich sehr über Feedback von den Benutzern der Seite. Bitte meldet Euch bei mir wenn Dinge nicht funktionieren wie sie sollten, wenn die Bedienung der Seite unverständlich ist oder ihr Vorschläge für Verbesserungen und neue Features habt.</p>

			<p><a target="_blank" href="http://blog.tipp2.net/?page_id=10">Zum Feedback-Bereich im Blog</a></p>
		</div>
	</div>

	<div class="span4">
		<%= render 'next_games' %>
	</div>
</div>

app/views/pages/admin.html.erb
<h2>Admin Übersicht</h2>

<p>Willkommen im streng bewachten Kernstück von tipp2!</p>

<h3>Menü</h3>

<div class="row">
	<div class="span4">

		<ul class="nav nav-list">
			<li><%= link_to "Wettbewerbe, Spieltage oder Spiele bearbeiten", cups_path %></li>
			<li><%= link_to "Ergebnisse eintragen", :controller => "games", :action => "result_index"%></li>
			<li><%= link_to "Teams bearbeiten", teams_path %></li>
			<li><%= link_to "User bearbeiten", users_path %></li>
			<li><%= link_to "Communities bearbeiten", communities_path %></li>
			<li><%= link_to "Posts bearbeiten", posts_path %></li>
		</ul>
	</div>
	<div class="span8">
	</div>
</div>
<br>
<p>Hier kommt später eine Übersicht mit den aktuellen Spielen, um Ergebnisse direkt einzugeben.</p>

app/views/pages/home.html.erb
<div class="row">
	<% if user_signed_in? %>
			<div class="span8" id="user_news">
				<% if @user.community_id.nil? %>
					<%= render 'shared/community_menu' %>
					<%= render 'tipp2_news' %>
				<% else %>
					<%= render 'community_news' %>
				<% end %>
			</div>
	<% else %>
		<div class="span8" id="welcome">
			<div class="hero-unit">
				<%= render 'welcome' %>
			</div>
		</div>
	<% end %>

	<div class="span4">
		<%= render 'next_games' %>
	</div>

</div>

app/views/pages/impressum.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">
			<h2>Impressum</h2>

			<p>Dies ist ein privates Projekt von:</p>

			<p>Marc Otten</p>
			<p>Dortmund, Germany</p>
			<p>+49 170 210 41 78</p>
			<p><a target="_blank" href="http://22dev.de">22dev.de</a></p>
			<p><a class="btn btn-small" href="mailto:marc@22dev.de"><i class="icon-envelope icon-large"></i>E-Mail</a></p>
		</div>
	</div>

	<div class="span4">
		<%= render 'next_games' %>
	</div>
</div>

app/views/pages/rules.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">
			<h2>Spielregeln</h2>

			<p>Bei tipp2 tippen die Spieler auf Ergebnisse von Fussballspielen. Für richtige Tipps gibt es Punkte. Es geht darum, im Verlauf eines Wettbewerbes die meisten Punkte zu sammeln und so das Tippspiel zu gewinnen.</p>

			<h4>Punkteregeln</h4>

			<ul>
				<li>Tipps können bis zum Anstoß der Partie abgegeben werden</li>
				<li>Für ein genau richtig getipptes Ergebnis gibt es <b>3 Punkte</b>. (Beispiel: Ergebnis 3:1, Tipp 3:1)</li>
				<li>Für einen richtig getippten Torabstand gibt es <b>2 Punkte</b>. (Beispiel: Ergebnis 3:1, Tipp 2:0)</li>
				<li>Für eine richtig getippte Tendenz (Sieg, Unentschieden, Niederlage) gibt es <b>1 Punkt</b>. (Beispiel: Ergebnis 3:1, Tipp: 3:0)</li>
				<li>Bei Elfmeterschießen zählt gewonnenes Elfmeterschießen als ein Tor (Beispiel: Ergebnis nach Verlängerung 1:1, nach Elfmeterschießen 4:5 wird als 1:2 gewertet).</li>
			</ul>
		</div>
	</div>

	<div class="span4">
		<%= render 'next_games' %>
	</div>
</div>