config/routes.rb
Tipp5::Application.routes.draw do
  
  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :cups do
    member do
      get 'automate'
    end
    resources :rounds do
    end
  end

  resources :games do
    collection do
      get :result_index
    end
    member do
      get :fix_result
      put :save_result
    end
  end
  
  resources :bets

  resources :posts do
    collection do
      get :new_userpost
    end
  end

  resources :teams

  resources :communities do
    collection do
      get :kick_out
      get :invite
    end
  end

  
  root :to => 'pages#home'

  match '/admin',     :to => 'pages#admin'
  match '/userpage',  :to => 'pages#userpage'
  match '/adminpage', :to => 'pages#adminpage'
  match '/about',     :to => 'pages#about'
  match '/rules',     :to => 'pages#rules'
  match '/impressum', :to => 'pages#impressum'
  
  match '/abgabe',    :to => 'bets#abgabe'
  match '/uebersicht', :to => 'bets#index'
  match '/ranking',   :to => 'bets#ranking'

  match '/news',      :to => 'posts#news'

  match '/join',      :to => 'communities#join'
  match '/leave',     :to => 'communities#leave'

end

app/models/game.rb
 # -*- coding: utf-8 -*-
class Game < ActiveRecord::Base

	has_many :bets
	has_many :users, :through => :bets
	belongs_to :round
	belongs_to :cup
	has_many :teams

	validates :round_id,	:presence => true
	validates :kickoff, 	:presence => true
	validates :home_team,	:presence => true
	validates :away_team,	:presence => true
	validates_numericality_of :home_score, :only_integer => true, :allow_nil => true
	validates_numericality_of :away_score, :only_integer => true, :allow_nil => true

end

app/controllers/games_controller.rb
 # -*- coding: utf-8 -*-

class GamesController < ApplicationController

	before_filter :authenticate_admin!
	
	def index
		@title = "Übersicht Spiele"

		if params[:round_id].nil?
			next_game = Game.where("kickoff >= ?", Time.now).first
			@round = Round.find(next_game.round_id)
			@cup = Cup.find(@round.cup_id)
			@games = Game.where(:round_id => next_game.round_id).order('kickoff ASC')
		else
			@round = Round.find(params[:round_id])
			@cup = Cup.find(@round.cup_id)
			@games = Game.where(:round_id => params[:round_id]).order('kickoff ASC')
		end
	end

	def show
		@title = "Spiel anzeigen"
		@game = Game.find(params[:id])
		@round = Round.find(@game.round_id)
		@cup = Cup.find(@round.cup_id)
	end

	def new
		@title = "Spiel anlegen"
		@cup = Cup.find(params[:cup_id])
		@round = Round.find(params[:round_id])
		@game = Game.new
		@teams = Team.all
	end

	def edit
		@title = "Spiel bearbeiten"
		@game = Game.find(params[:id])
		@round = Round.find(@game.round_id)
		@cup = Cup.find(@round.cup_id)
		@teams = Team.all
	end

	def create
		@game = Game.new(params[:game])

		if @game.save
			flash[:success] = "Spiel erfolgreich erstellt."
			redirect_to @game
		else
			flash[:error] = "Fehler!"
			redirect_to :back
		end
	end

	def update
		@game = Game.find(params[:id])

		if @game.update_attributes(params[:game])
			flash[:success] = "Spiel bearbeitet."
			redirect_to @game
		else
			flash[:error] = "Fehler!"
			redirect_to :back
		end
	end

	def destroy
		Game.find(params[:id]).destroy
		flash[:success] = "Spiel gelöscht"
		redirect_to :back
	end

	def result_index
		@title = "Ergebnisse eintragen"
		@games = Game.where( :home_score => nil).order(:kickoff).limit(36)
	end

	def fix_result
		@title = "Ergebnis eintragen"
		@game = Game.find(params[:id])
	end

	def save_result
		@game = Game.find(params[:id])
		@bets = Bet.find_all_by_game_id(@game.id)

		if @game.update_attributes(params[:game])
			flash[:success] = "Ergebnis eingetragen."
			# do some point-updating here
			@bets.each do |bet|
				p = points_per_game(@game.home_score, @game.away_score, bet.home_bet, bet.away_bet)
				bet.points = p
				bet.save
				flash[:success] = "Punkte verteilt."
			end
			# Spieltagszusammenfassung erstellen, wenn Spieltag vorbei
			if round_over(@game) == true
				post_round_summary(@game)
			end

			head = "#{Team.find(@game.home_team).name} - #{Team.find(@game.away_team).name} #{@game.home_score}:#{@game.away_score}"
			Post.create(:headline => head, :category => 'System', :content => '[System: Punkte verteilt.]')
			redirect_to result_index_games_path
		else
			flash[:error] = "Fehler!"
			redirect_to :back
		end
	end

end

app/helpers/games_helper.rb
 # -*- coding: utf-8 -*-
module GamesHelper

	

end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :round_id, :value => @round.id %>

  <h4>Wettbewerb: <%= @cup.name %></h4>
  <h4>Spieltag: <%= @round.name %></h4>
  <br><br>

  <div class="field">
    <%= f.label :kickoff %><br />
    <%= f.datetime_select :kickoff %>
  </div>
  <div class="field">
    <%= f.label :home_team %><br />
    <%= collection_select(:game, :home_team, @teams, :id, :name, options ={:prompt => "Team auswählen"}) %>
  </div>
  <div class="field">
    <%= f.label :away_team %><br />
    <%= collection_select(:game, :away_team, @teams, :id, :name, options ={:prompt => "Team auswählen"}) %>
  </div>
  <!--hier waren mal die felder fuer die Ergebnisse -->
  <% unless @game.away_score.nil? %>
    <div class="field">
      <%= f.label :home_score %><br />
      <%= f.number_field :home_score %>
    </div>
    <div class="field">
      <%= f.label :away_score %><br />
      <%= f.number_field :away_score %>
    </div>
  <% end -%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Spiel bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/fix_result.html.erb
<h1>Spiel bearbeiten</h1>

<%= form_for(@game, :url => save_result_game_path(@game)) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fixture">
  	<%= Team.find(@game.home_team).name %> : <%= Team.find(@game.away_team).name %>

   <div class="field">
    <%= f.label :home_score %><br />
    <%= f.number_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br />
    <%= f.number_field :away_score %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to "Ergebnisse eintragen", :controller => "games", :action => "result_index"%>

app/views/games/index.html.erb
<h3>Spiele bearbeiten</h3>

<h4>Wettbewerb: <%= @cup.name %></h4>
<h4>Spieltag: <%= @round.name %></h4>

<table class="table table-striped table-condensed">
  <tr>
    <th>Cup</th>
    <th>Round</th>
    <th>Kick Off</th>
    <th>Home Team</th>
    <th>Away Team</th>
    <th>openLiga-ID</th>
    <th>Home Score</th>
    <th>Away Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
    <% round = Round.find(game.round_id) %>
    <% cup = Cup.find(round.cup_id) %>
    <tr>
        <td><%= cup.name %></td>
        <td><%= round.name %></td>
        <td><%= game.kickoff.strftime("%d.%m.%y %H:%M") %></td>
        <td><%= Team.find(game.home_team).name %></td>
        <td><%= Team.find(game.away_team).name %></td>
        <td><%= game.open_liga_id %></td>
        <td><%= game.home_score %></td>
        <td><%= game.away_score %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, :confirm => 'Sicher?', :method => :delete %></td>
      </tr>
    <% end %>
</table>

<br />

<%= link_to 'Neues Spiel', new_game_path(:cup_id => @cup.id, :round_id => @round.id) %> <br />
<%= link_to 'Spieltagsübersicht', cup_rounds_path(@cup) %><br />
<%= link_to 'Zurück zur Admin Übersicht', admin_path %>

app/views/games/new.html.erb
<h1>Neues Spiel eingeben</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path(:round_id => @round.id) %>

app/views/games/result_index.html.erb
<h3>Ergebnisse eintragen</h3>

<table class="table table-striped table-condensed">
  <tr>
    <th>Kick Off</th>
    <th>Home Team</th>
    <th>Away Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.kickoff.strftime("%d.%m.%y %H:%M") %></td>
    <td><%= Team.find(game.home_team).name %></td>
    <td><%= Team.find(game.away_team).name %></td>
    <td><%= link_to "Ergebnis eintragen", fix_result_game_path(game) %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Zurück zur Admin Übersicht', admin_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Anstoß:</b>
  <%= @game.kickoff.strftime("%d.%m.%y %H:%M") %>
</p>

<p>
  <b>Wettbewerb:</b>
  <%= @cup.name %>
</p>

<p>
  <b>Spieltag:</b>
  <%= @round.name %>
</p>

<p>
  <b>Heim:</b>
  <%= Team.find(@game.home_team).name %>
</p>

<p>
  <b>Auswärts:</b>
  <%= Team.find(@game.away_team).name %>
</p>

<p>
  <b>Home score:</b>
  <%= @game.home_score %>
</p>

<p>
  <b>Away score:</b>
  <%= @game.away_score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path(:round_id => @round.id) %>