config/routes.rb
Tipp5::Application.routes.draw do
  
  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :cups do
    member do
      get 'automate'
    end
    resources :rounds do
    end
  end

  resources :games do
    collection do
      get :result_index
    end
    member do
      get :fix_result
      put :save_result
    end
  end
  
  resources :bets

  resources :posts do
    collection do
      get :new_userpost
    end
  end

  resources :teams

  resources :communities do
    collection do
      get :kick_out
      get :invite
    end
  end

  
  root :to => 'pages#home'

  match '/admin',     :to => 'pages#admin'
  match '/userpage',  :to => 'pages#userpage'
  match '/adminpage', :to => 'pages#adminpage'
  match '/about',     :to => 'pages#about'
  match '/rules',     :to => 'pages#rules'
  match '/impressum', :to => 'pages#impressum'
  
  match '/abgabe',    :to => 'bets#abgabe'
  match '/uebersicht', :to => 'bets#index'
  match '/ranking',   :to => 'bets#ranking'

  match '/news',      :to => 'posts#news'

  match '/join',      :to => 'communities#join'
  match '/leave',     :to => 'communities#leave'

end

app/models/community.rb
class Community < ActiveRecord::Base
	has_many :users

	validates :name, 		:presence 	=> true,
							:length		=> { :within => 6..30},
							:uniqueness => true

	validates :password, 	:presence 		=> true,
							:confirmation	=> true,
							:length			=> { :within => 6..20}

	validates :admin_id, 	:presence 		=> true
	validates_numericality_of 	:admin_id, :only_integer => true

end

app/controllers/communities_controller.rb
# encoding: UTF-8
class CommunitiesController < ApplicationController
	#ACHTUNG: Wer kann was wann sehen? Authenticate 
	#nochmal überarbeiten
	before_filter :authenticate_admin!, :only => [:index]
	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :join, :leave, :invite] 
	before_filter :authenticate_any!, :only => [:show, :destroy]


	def index
		@title = "Übersicht Communities"
		@communities = Community.all
	end

	def new
		@title = "Community erstellen"
		@user = current_user
		@community = Community.new
	end

	def show
		@title = "Community Ansicht"
		@community = Community.find(params[:id])
		@admin = User.find(@community.admin_id)
		@members = User.where(:community_id => @community.id)
	end

	def edit
		@title = "Community bearbeiten"
		@user = current_user
		@community = Community.find(params[:id])
		if @community.admin_id != @user.id
			flash[:error] = "Community darf nur vom Administrator bearbeitet werden!"
			redirect_to root_path
		end
	end

	def invite
		@user = current_user
		@community = Community.find(current_user.community_id)
		unless params[:address].nil?
			@address = params[:address]
			CommunityMailer.community_invitation(@address, @user, @community).deliver
			flash[:success] = "E-Mail Einladung an " + @address + " versendet."
		end
	end 


	def create
		@community = Community.new(params[:community])
		@user = current_user

		if @community.save
			@user.community_id = @community.id
			@user.save
			flash[:success] = "Community erfolgreich erstellt."
			redirect_to @community
		else
			flash[:error] = "Fehler!"
			redirect_to :back
		end
	end

	def update
		@community = Community.find(params[:id])
		if @community.name_changed?
			@name_change = true
		end
		if @community.password_changed?
			@password_change = true
		end
		if @community.update_attributes(params[:community])
			flash[:success] = "Community bearbeitet."
			if @name_change == true
				Post.create(headline: "Name der Community geändert", 
							category: "com" + @community.id.to_s, 
							content: "Der Admin der Community hat den Namen der Community geändert. Die Community heißt nun " + @community.name + ".")
			end
			if @password_change == true
				Post.create(headline: "Passwort der Community geändert", 
							category: "com" + @community.id.to_s, 
							content: "Der Admin der Community hat das Passwort der Community geändert. Das neue Passwort ist " + @community.password + ". Das Passwort wird benötigt, um der Community beizutreten.")
			end
			redirect_to @community
		else
			flash[:error] = "Fehler!"
			redirect_to :back
		end
	end

	def destroy
		@community = Community.find(params[:id])
		@users = @community.users
		@users.each do |user|
			user.community_id = nil
			user.save
		end
		@community.destroy
		flash[:success] = "Community gelöscht"
		redirect_to root_path
	end

	def join
		@user = current_user
		if params[:com_search].nil?
			@community = nil
		else
			@community =  Community.find_by_name(params[:com_search])
		end
		@password = params[:pass]
		unless params[:com_search].nil?
			if @community.nil?
				flash[:error] = "Community nicht gefunden!"
				redirect_to :back
			else
				unless @password.nil?
					if @password === @community.password
						@user.community_id = @community.id
						@user.save
						flash[:success] = "Community beigetreten!"
						Post.create(	headline: "Neuer Mitspieler", 
										category: "com" + @community.id.to_s,
										content: @user.username + " ist der Community beigetreten. Herzlich Willkommen!")
						redirect_to root_path
					else
						flash[:error] = "Name und Passwort der Community passen nicht zusammen"
						redirect_to :back
					end
				end
			end
		end
	end

	def leave
		@user = current_user
		@community = Community.find(@user.community_id)
		if @user.id === @community.admin_id
			if @community.users.count < 2
				@community.destroy
				@user.community_id = nil
				@user.save
				flash[:success] = "Community gelöscht!"
				redirect_to root_path
			else
				@user.community_id = nil
				@user.save
				@new_admin = @community.users.first
				@community.admin_id = @new_admin.id
				@community.save
				flash[:success] = "Aus Community ausgetreten!"
				Post.create(	headline: "Admin ausgetreten", 
								category: "com" + @community.id.to_s,
								content: @user.username + " hat die Community verlassen. Da " + @user.username + " der Admin der Community war, musste ein neuer Admin bestimmt werden. Neuer Community-Admin ist " + @new_admin.username + ".")
				redirect_to root_path
			end
		else
			@user.community_id = nil
			@user.save
			flash[:success] = "Aus Community ausgetreten!"
			Post.create(	headline: "Mitspieler ausgetreten", 
							category: "com" + @community.id.to_s,
							content: @user.username + " hat die Community verlassen.")
			redirect_to root_path
		end
	end

	def kick_out
		@community = Community.find(current_user.community_id)
		if current_user.id === @community.admin_id
			@user = User.find(params[:user_id])
			@user.community_id = nil
			@user.save
			flash[:success] = @user.username + " aus der Community rausgeworfen!"
			Post.create(	headline: "Mitspieler rausgeworfen", 
							category: "com" + @community.id.to_s,
							content: @user.username + " wurde vom Admin aus der Community geworfen.")
			redirect_to @community
		else
			flash[:error] = "Du hast nicht die Rechte, jemanden aus der Community zu werfen!"
			redirect_to @community
		end
	end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for(@community) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :admin_id, :value => @user.id %>

  <div class="field">
    <%= f.label :name%><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Community-Passwort" %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">
			<h2>Community bearbeiten</h2>

			<%= render 'form' %>
			
		</div>
	</div>
</div>

app/views/communities/index.html.erb
<h3>Communities anzeigen</h3>

<table class="table table-striped table-condensed">
  <tr>
    <th>Name</th>
    <th>Admin User</th>
    <th>Passwort</th>
    <th>Erstellt am</th>
    <th>Mitglieder</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @communities.each do |community| %>
    <tr>
        <td><%= community.name %></td>
        <td><%= User.find(community.admin_id).username  %></td>
        <td><%= community.password %></td>
        <td><%= community.created_at.strftime("%d.%m.%y") %></td>
        <td><%= community.users.count %></td>
        <td><%= link_to 'ansehen', community %></td>
        <td><%= link_to 'löschen', community, :confirm => 'Sicher?', :method => :delete %></td>
      </tr>
    <% end %>
</table>

<br />

<%= link_to 'Zurück zur Admin Übersicht', admin_path %>

app/views/communities/invite.html.erb
<h1>Leute einladen</h1>

<p>Gebe in das Eingabefeld eine E-Mail Adresse ein, um eine Einladung mit den Zugangsdaten deiner Community an diese Adresse zu senden.</p>

<%= form_tag invite_communities_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :address, params[:address] %><br>
		<%= submit_tag "einladen", :class => "btn" %>
	</p>
<% end %>

<%= link_to "zurück", @community %>

app/views/communities/join.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">
			<h2>Community beitreten</h2>

			<p>Mit Communities kannst du tipp2 mit deinen Freunden spielen. Gehörst Du zu keiner Community, werden nur deine Tipps und deine Punkte angezeigt.</p>

			<p>Um einer Community beizutreten, musst du den Namen und das Passwort der Community kennen.</p>

			<%= form_tag join_path, :method => 'get' do %>

				<p>
					<%= label_tag "Communityname" %> 
					<%= text_field_tag :com_search, params[:com_search] %>
					<%= label_tag "Communitypasswort" %> 
					<%= password_field_tag :pass, params[:pass] %>
					<%= submit_tag "Community beitreten", :name => nil %>
				</p>
			<% end %>
			<ul>
			<% unless @community.nil? %>
				<% @community.each do |c|%>
					<li><%= c.name %></li>
				<% end %>
			<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/communities/new.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">
			<h2>Neue Community gründen</h2>

			<p>Mit Communities kannst du tipp2 mit deinen Freunden spielen. Gehörst Du zu keiner Community, werden nur deine Tipps und deine Punkte angezeigt.</p>

			<p>Um eine Community zu gründen, denke Dir einen Namen aus und vergebe ein Passwort. Mit dem Namen und dem Passwort können andere Spieler deiner Community beitreten.</p>

			<p>Als Gründer der Community bist du gleichzeitig Administrator. Das heisst, du kannst den Namen und das Passwort der Community ändern. Ebenfalls kannst du Spieler aus der Community rauswerfen. Dies solltest du aber nur machen, wenn es hierfür einen triftigen Grund gibt.</p>

			<%= render 'form' %>
			
		</div>
	</div>
</div>

app/views/communities/show.html.erb
<div class="row">
	<div class="span8">
		<div class="main_content">
			<h2>Community <%= @community.name %></h2>

			<p>Community-Administrator: <%= @admin.username %></p>

			<p><%= @members.count %> Mitglieder:</p>

			<ul>
				<% @members.each do |m| %>
					<li><%= link_to m.username, user_path(m) %>

					 | <a href="mailto: <%= m.email %>">E-Mail schreiben</a>
						<% if current_user.id === @community.admin_id %>
								<% unless m.id === current_user.id %>
									 | <%= link_to "Spieler aus der Community werfen",  kick_out_communities_path(:user_id =>m.id), :confirm => 'Sicher? Du solltest hierfür gute Gründe haben!' %>
								<% end %>
						<% end %>
					</li>
						<!-- hier muss später das Profil verlinkt sein -->
				<% end %>
			</ul>

			<% if user_signed_in? %>
				<% if current_user.id === @community.admin_id %>
					<h3>Community-Admin Optionen</h3>

					<p>Du bist Administrator dieser Community.</p>

					<p><%= link_to "Leute einladen", invite_communities_path, :class => "btn" %></p>

					<p><%= link_to "Name oder Passwort ändern", edit_community_path, :class => "btn" %></p>

					<p><%= link_to 'Community löschen', @community, :confirm => 'Sicher? Alle restlichen Mitglieder werden aus der Community entfernt! Du kannst auch unter deinem Nutzer-Profil einfach aus der Community austreten und ein anderer Spieler wird Administrator.', :class => "btn", :method => :delete %></p>
				<% end %>
			<% end %>
			<% if admin_signed_in? %>
				<%= link_to 'Zurück zur Community Übersicht', communities_path %>
			<% end %>
		</div>
	</div>
</div>