config/routes.rb
Tipp5::Application.routes.draw do
  
  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  resources :cups do
    member do
      get 'automate'
    end
    resources :rounds do
    end
  end

  resources :games do
    collection do
      get :result_index
    end
    member do
      get :fix_result
      put :save_result
    end
  end
  
  resources :bets

  resources :posts do
    collection do
      get :new_userpost
    end
  end

  resources :teams

  resources :communities do
    collection do
      get :kick_out
      get :invite
    end
  end

  
  root :to => 'pages#home'

  match '/admin',     :to => 'pages#admin'
  match '/userpage',  :to => 'pages#userpage'
  match '/adminpage', :to => 'pages#adminpage'
  match '/about',     :to => 'pages#about'
  match '/rules',     :to => 'pages#rules'
  match '/impressum', :to => 'pages#impressum'
  
  match '/abgabe',    :to => 'bets#abgabe'
  match '/uebersicht', :to => 'bets#index'
  match '/ranking',   :to => 'bets#ranking'

  match '/news',      :to => 'posts#news'

  match '/join',      :to => 'communities#join'
  match '/leave',     :to => 'communities#leave'

end

app/views/layouts/_footer.html.erb
 <div id="footer">
	<ul id="footer_nav">
		<li id="li_footer_nav"><a target="_blank" href="http://blog.tipp2.net/">Blog</a></li>
		<li id="li_footer_nav"><a href="http://http://blog.tipp2.net/?page_id=10/">Feedback</a></li>
		<li id="li_footer_nav"><%= active_link_to "About", about_path %></li>
		<li id="li_footer_nav"><%= active_link_to "Spielregeln", rules_path %></li>
		<li id="li_footer_nav"><%= active_link_to "Impressum", impressum_path %></li>
	</ul>

	<div id="footer_info">
		<div id="footer_logo">
    		<a target="_blank" href="http://22dev.de"><%= image_tag("22logo_4_tiny.png", :alt => "twentytwo develpment", :size => "120x44") %></a>
  		</div>
		<div id="footer_version">
			<p>made by</p>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <div id="logo">
    <% logo = image_tag("tipp2_logo.png", :alt => "tipp2") %>
    <%= link_to logo, root_path %>
  </div>
  <div id="head_right">
    <div id="session_info">
      <% if user_signed_in? %>
          Angemeldet als <%= current_user.username %> - <%= link_to '<i class="icon-user"></i>'.html_safe, edit_user_registration_path, :title => "Profil bearbeiten" %> <%= active_link_to "Profil bearbeiten", edit_user_registration_path %> - 
          <%= link_to "abmelden", destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to "registrieren", new_user_registration_path %> oder
          <%= link_to "anmelden", new_user_session_path %>
      <% end %>

      <% if admin_signed_in? %>
          <br> Angemeldet als Admin <%= current_admin.username %>, 
          <%= link_to "abmelden", destroy_admin_session_path, :method => :delete %> <%= link_to 'Backend', admin_path %>
      <% end %>
    </div>
    </br>
    <div id="timenow">
      <%= Time.now.strftime("%d.%m.%y %H:%M") %> 
    </div>
  </div>
  <div id="navigation">
    <ul>
      <li id="li_home"><%= active_link_to "Home", root_path %></li>
      <li id="li_abgabe"><%= active_link_to "Tippabgabe", abgabe_path %></li>
      <li id="li_uebersicht"><%= active_link_to "Tippübersicht", uebersicht_path %></li>
      <li id="li_uebersicht"><%= active_link_to "Spielstand", ranking_path %></li>
    </ul>
  </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tipp2 - Das Fussball Tippspiel 
    <% unless @title.nil? %>
      | <%= @title %>
    <% end %>
  </title>
  
  <link href="/public/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

  <%= analytics_init if Rails.env.production? %>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
	
	<div class="container">

    <%= render 'layouts/header' %>

  	<div class="main">

  		<% flash.each do |key, value| %>
      		<div class="alert alert-<%= key %>"><%= value %></div>
    		<% end %>

  		<%= yield %>

  	</div>
    
    <%= render 'layouts/footer' %>
    
	</div>

</body>
</html>